[[{
    "date":"2013-2-4",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-4",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-4",
    "EID":"ACE_EMP_0008",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"PROJ_0013",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-4",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-4",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Vacation"],
    "WH":[4],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-4",
    "EID":"ACE_EMP_0002",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"PROJ_0057",
    "WO":["TNE"],
    "WH":[6],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":[],
    "WH":[],
    "TD":[],
    "TP":[]
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-5",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-5",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-5",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[6],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-5",
    "EID":"ACE_EMP_0002",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"PROJ_0057",
    "WO":["TNE"],
    "WH":[6],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":[],
    "WH":[],
    "TD":[],
    "TP":[]
},{
    "PID":"General",
    "WO":[],
    "WH":[],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0008",
    "WO":["PROGRAMMING"],
    "WH":[2],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-5",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-6",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-6",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-6",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Vacation"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-6",
    "EID":"ACE_EMP_0002",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL","Training"],
    "WH":[4,2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0057",
    "WO":["TNE"],
    "WH":[2],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-6",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_EMP_0008",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0013",
    "WO":[],
    "WH":[],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[6],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_EMP_0002",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"PROJ_0011",
    "WO":["PROGRAMMING"],
    "WH":[1],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0055",
    "WO":["PROGRAMMING"],
    "WH":[1],
    "TD":[],
    "TP":[]
},{
    "PID":"General",
    "WO":["GENERAL","Training"],
    "WH":[1,5],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-7",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-8",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-8",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-8",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[6],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-8",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL","Vacation"],
    "WH":[4,4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_CON_0001",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[8],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_EMP_0008",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[2],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0013",
    "WO":[],
    "WH":[],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_INT_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["Training"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_EMP_0011",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[1],
    "TD":[],
    "TP":[]
},{
    "PID":"PROJ_0060",
    "WO":["GENERAL"],
    "WH":[3],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_EMP_0002",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
}],[{
    "date":"2013-2-9",
    "EID":"ACE_EMP_0003",
    "I":8.3,
    "O":5.3,
    "S":0
},{
    "PID":"General",
    "WO":["GENERAL"],
    "WH":[4],
    "TD":[],
    "TP":[]
}]]