var v ={
    "query":{
        "count":1,
        "created":"2012-04-02T06:02:39Z",
        "lang":"en-US",
        "results":{
            "quote":{
                "symbol":"XME",
                "Ask":"49.89",
                "AverageDailyVolume":"3550630",
                "Bid":"49.53",
                "AskRealtime":"49.89",
                "BidRealtime":"49.53",
                "BookValue":"0.00",
                "Change_PercentChange":"+0.04 - +0.08%",
                "Change":"+0.04",
                "Commission":null,
                "ChangeRealtime":"+0.04",
                "AfterHoursChangeRealtime":"N/A - N/A",
                "DividendShare":"0.516",
                "LastTradeDate":"3/30/2012",
                "TradeDate":null,
                "EarningsShare":"0.00",
                "ErrorIndicationreturnedforsymbolchangedinvalid":null,
                "EPSEstimateCurrentYear":"0.00",
                "EPSEstimateNextYear":"0.00",
                "EPSEstimateNextQuarter":"0.00",
                "DaysLow":"48.96",
                "DaysHigh":"50.24",
                "YearLow":"40.17",
                "YearHigh":"77.44",
                "HoldingsGainPercent":"- - -",
                "AnnualizedGain":null,
                "HoldingsGain":null,
                "HoldingsGainPercentRealtime":"N/A - N/A",
                "HoldingsGainRealtime":null,
                "MoreInfo":"cnpIed",
                "OrderBookRealtime":null,
                "MarketCapitalization":null,
                "MarketCapRealtime":null,
                "EBITDA":"0",
                "ChangeFromYearLow":"+9.55",
                "PercentChangeFromYearLow":"+23.77%",
                "LastTradeRealtimeWithTime":"N/A - 49.72",
                "ChangePercentRealtime":"N/A - +0.08%",
                "ChangeFromYearHigh":"-27.72",
                "PercebtChangeFromYearHigh":"-35.80%",
                "LastTradeWithTime":"Mar 30 - 49.72",
                "LastTradePriceOnly":"49.72",
                "HighLimit":null,
                "LowLimit":null,
                "DaysRange":"48.96 - 50.24",
                "DaysRangeRealtime":"N/A - N/A",
                "FiftydayMovingAverage":"51.2814",
                "TwoHundreddayMovingAverage":"51.7262",
                "ChangeFromTwoHundreddayMovingAverage":"-2.0062",
                "PercentChangeFromTwoHundreddayMovingAverage":"-3.88%",
                "ChangeFromFiftydayMovingAverage":"-1.5614",
                "PercentChangeFromFiftydayMovingAverage":"-3.04%",
                "Name":"SPDR S&P Metals &",
                "Notes":null,
                "Open":"50.14",
                "PreviousClose":"49.68",
                "PricePaid":null,
                "ChangeinPercent":"+0.08%",
                "PriceSales":null,
                "PriceBook":null,
                "ExDividendDate":"Mar 16",
                "PERatio":null,
                "DividendPayDate":"Mar 28",
                "PERatioRealtime":null,
                "PEGRatio":null,
                "PriceEPSEstimateCurrentYear":null,
                "PriceEPSEstimateNextYear":null,
                "Symbol":"XME",
                "SharesOwned":null,
                "ShortRatio":null,
                "LastTradeTime":"4:00pm",
                "TickerTrend":" =+=+== ",
                "OneyrTargetPrice":null,
                "Volume":"2862263",
                "HoldingsValue":null,
                "HoldingsValueRealtime":null,
                "YearRange":"40.17 - 77.44",
                "DaysValueChange":"- - +0.08%",
                "DaysValueChangeRealtime":"N/A - N/A",
                "StockExchange":"PCX",
                "DividendYield":"1.04",
                "PercentChange":"+0.08%"
            }
        }
    }
}