name: aceengineer_website
channels:
  - defaults
  - anaconda
dependencies:
  - python
  - pandas
  - pip
  - pip:
      - Flask==1.1.2
      - flask_wtf
      - flask_httpauth
      - flask_restful
      - Werkzeug==1.0.1
      - markupsafe==2.0.1
      - email_validator==1.3.0
