# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY api/requirements.txt ./
RUN apt-get install ca-certificates
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --no-cache-dir  -r ./requirements.txt
COPY api/ ./
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
