SET search_path TO stocks;
drop table if exists stocks.keys;

create table IF not exists keys(
    stock_id        INT         GENERATED BY DEFAULT AS IDENTITY,
	ticker          text        not null,
	cik             varchar(10) null,
    name            text        null,
    exchange        text        null,
    sector          text        null,
    cusip           text        null,

    updated_time    timestamp   null,
    status          json        null,

	CONSTRAINT keys_ticker_unique UNIQUE(ticker)
	);
